### ISSUE TITLE
Set a maximum limit of letter in the text area.

### ISSUE THREAD

**Issue by priyanshu-solon** [Aapush01/QReasy#12]
Setting a maximum limit of letter in the text area will make the QR code generation less buggy and won't crash or freeze after we add many letters intentionally or unintentionally.

**Comment by Aapush01** [comment]
After reviewing the proposed feature, I believe it might not align with the project's current goals and could introduce potential complexities. It might be worth considering alternatives or reassessing the priority of this feature.
