### ISSUE TITLE
Implement Dark Mode

### ISSUE THREAD

**Issue by priyanshu-solon** [Aapush01/QReasy#13]
Offer light and dark mode themes.

**Comment by Aapush01** [comment]
I believe you're well-suited to handle this task, so I'm assigning this issue to you. Please feel free to reach out if you have any questions or need clarification on the requirements.

**Comment by priyanshu-solon** [comment]
The BackgroundLines may get affected by the dark mode
ignore else...
![image](https://github.com/user-attachments/assets/f633fee3-eed5-4045-8fd8-d42f70ae5e87)
