### ISSUE TITLE
 Add Option to Customize QR Code Design

### ISSUE THREAD

**Issue by Aapush01** [Aapush01/QReasy#5]
### Description:
Add the ability for users to **customize the appearance** of the QR code by changing colors, shapes, and patterns.

### Expected Behavior:
- Users can select from predefined colors or enter a custom color code.
- Users can choose different patterns (square, dot, etc.) for the QR code blocks.

### Tasks:
1. Create a modal or panel for design options (color, pattern).
2. Implement the ability to change QR code colors and patterns.
3. Ensure QR code functionality remains intact with new designs.
4. Add preview functionality to show users what the customized QR code looks like.

### Additional Notes:
- Provide defaults for color and pattern if none are selected.
- Ensure designs are visually accessible.

**Comment by priyanshu-solon** [comment]
![Untitled](https://github.com/user-attachments/assets/15e0e321-12ba-419e-a7ec-8b3cd4016a99)

1. Color Customization:
Added two dropdowns for selecting foreground and background colors from the following lists:
- Foreground Colors: Black, Red, Blue, Green
- Background Colors: White, Pink, Yellow, Lavender, Honeydew

2.  Random Color Selection:
- Introduced a new handleRandomColors function that randomly assigns colors to both foreground and background from the respective arrays.

_More colors can be added but the scanner should be able to scan the QR Code as lighter foreground and darker background can be difficult for the scanner to understand._

**Comment by Aapush01** [comment]
Good work. @priyanshu-solon create a PR
